coded
Szpytowski/Javascript-functions pull request #1
Opened 2024-09-18 10:28 UTC by Szpytowski

2024-09-18 18:47 UTC, Solnick requested changes

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +function getCircleArea(radius){
```suggestion
function getCircleArea(radius) {
```

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +
Don't leave more than one new line sign between code lines. One is enough to make the code more pleasant to read, 2 new lines is too many.

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +const quarterOf = (month) => {
How did you come up with the `=>` notation?

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +    return minutes / 60
remember about `;`

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +    if (num >0) {
```suggestion
    if (num > 0) {
```

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +    return str.slice(1, -1);
How did you found this `-1` solution?

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +function basicOp(operation, value1, value2){
`value` is not a descriptive argument name. Please use better naming, it should be self-explenatory

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +    const century = Math.ceil (year / 100);
```suggestion
    const century = Math.ceil(year / 100);
```

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +function rockPaperScissors(player1, player2) {
player is not a descriptive name. Maybe player1Move?

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +    } else {
do you remember what to do when there is the else statement with the return statement?

2024-09-18 18:47 UTC, Solnick commented on js/app.js
> +        return "null";
`null` is an actual valid JS value, you don't need to wrap it as a string.

2024-09-19 01:26 UTC, Szpytowski commented on js/app.js
> +const quarterOf = (month) => {
The solutions I had weren't working, so I googled it how to calculate quarter of the month in js. And found that on multiple examples they were using the => notation 
https://stackoverflow.com/questions/74586033/how-can-i-find-what-quarter-of-the-year-a-month-is-in-based-on-the-number-the-mo

2024-09-25 08:57 UTC, Szpytowski commented on js/app.js
> +function basicOp(operation, value1, value2){
Examples(Operator, value1, value2) --> output 
I copied it from the assignment. I will call it first and second number

2024-10-02 15:18 UTC, Solnick requested changes
Please adjust the code according to this comment https://github.com/Szpytowski/Javascript-functions/pull/1#discussion_r1765541360

2024-10-17 15:40 UTC, Solnick approved these changes

2024-11-11 10:43 UTC, merged